packages/web/cpp/renderer.cpp
The thorvg update() method for frames has been modified. It will now return InsufficientCondition if the frame value is the same as the previous one.
- [] This is something we need to do.
=> renderer: updated frame change logic.

packages/web/README.md
=> docs: ✏️ add README live example

.changeset/dirty-planes-repair.md, .changeset/ninety-peaches-divide.md, .changeset/violet-hairs-rule.md, .changeset/yellow-windows-marry.md, apps/dotlottie-web-example/src/main.ts, packages/web/src/dotlottie.ts
This PR addresses few issues in the animation playback logic where animations were not resuming smoothly from their last progress point. Previously, when playback was paused and then resumed, the animation did not continue from the exact frame where it was interrupted. Instead, it either restarted from the beginning or exhibited frame jumps.
Changes:
Adjustment in `play` Method: Modified the logic to calculate the correct `_beginTime` based on the current `_elapsedTime` and `_speed`. This ensures that when the play method is called after a pause or stop, the animation resumes seamlessly from the exact point it was paused.
Refinement in `setSpeed` Method: Implemented a recalibration of `_beginTime` when the animation speed is adjusted during playback. This change prevents the animation …
=> fix: 🐛 resume animation playback from last progress point

.changeset/fluffy-trees-share.md, apps/dotlottie-web-example/src/main.ts, packages/web/README.md, packages/web/src/dotlottie.ts
introduces two new methods, `freeze` and `unfreeze`, to the `DotLottie` class. These methods enhance the control over animation playback by allowing animations to be temporarily halted and resumed without altering their current state or frame.
=> feat: 🎸 freeze & unfreeze methods

.changeset/lazy-items-play.md, packages/web/src/dotlottie.ts, packages/web/src/wasm/index.ts
* Now only creates a new ImageData when the buffer size changes, reusing the previous ImageData to avoid unnecessary allocations.
* The ThorVG buffer is guaranteed to be an 8-bit unsigned integer ranging from 0 to 255, so there is no need to allocate a new Uint8ClampedArray for casting, as the values won't exceed 255 or fall below 0.
After
Before
=> perf: ⚡️ skip re-allocating new ImageData & Uint8ClampedArray for each frame

.changeset/spotty-forks-battle.md, packages/web/src/utils.ts
if the content-type of the provided url is either a json or plain text, assume it's for a lottie json and let the renderer try to load it, if it fails to load then a loadError event would be emitted
=> fix: 🐛 load animation url with response content-type of text/plain

.changeset/thick-pumas-stare.md, packages/web/src/dotlottie.ts
Issue:
- Unable to load from url if the response's content-type contains anything more than `media-type`.
- For example, `text/plain` works but `text/plain; charset=utf-8` doesn't.
- [Test File](https://raw.githubusercontent.com/thorvg/thorvg/main/examples/resources/lottie/seawalk.json)
=> fix: 🐛 improve content-type parsing when loading from a url

.changeset/smart-garlics-approve.md, apps/dotlottie-react-example/src/App.tsx, packages/react/src/use-dotlottie.tsx
This pull request optimizes the DotLottieReact component by ensuring that the animation only starts playing when the canvas is within the viewport initially. If the canvas is outside the viewport, the animation will remain frozen until it becomes visible.
Changes:
- Added logic to check if the canvas is initially within the viewport using `getBoundingClientRect()`
=> feat(react): 🎸 optimize animation playback based on initial visibility

.changeset/wicked-starfishes-shop.md, packages/svelte/src/lib/Dotlottie.svelte, packages/svelte/src/routes/+page.svelte
Disable runes in svelte components to prevent compiler issues when running on runes mode.
Fixes #216
=> fix(svelte): disable runes in components

.github/workflows/main.yml, apps/dotlottie-web-example/src/main.ts, packages/web/src/worker/dotlottie.ts, packages/web/src/worker/dotlottie.worker.js, packages/web/tests/dotlottie-worker.test.ts, packages/web/types.d.ts
Changes: 
- Use the local wasm file, not the one from the CDN when running tests
=> chore(web): 🤖 fix DotLottieWorker failing tests

.changeset/bright-moles-heal.md, packages/web/src/dotlottie.ts, packages/web/src/worker/dotlottie.ts
When calling startStateMachine multiple times, the pointer event listeners on the canvas were being duplicated.
Discovery method:
- Loading an animation, start its state machine
- Use same dotLottie instance to load a different animation and state machine
- Click on animation, causing multiple pointerEvents to be sent to the state machine
=> fix: sm event listener duplication

.changeset/shaggy-cups-cross.md, package.json, packages/react/tsup.config.cjs, packages/web/tsup.config.cjs
Changes:
- Build dotlottie-web and dotlottie-react for ES2015 instead of ES2020.
- This resolves issues on platforms that don't support ES2020 by default, ensuring compatibility with ES6.
- Added a babel example to illustrate cases where ES2020 features, such as optional chaining, are not supported.
=> chore(web|react): update build target from ES2020 to ES2015

.changeset/mean-dolls-brush.md, .github/workflows/main.yml, packages/react/package.json, packages/react/src/dotlottie-worker.tsx, packages/react/src/dotlottie.tsx, packages/react/src/use-dotlottie-worker.tsx, packages/react/src/use-dotlottie.tsx, packages/react/tsconfig.build.json, packages/react/tsconfig.json, pnpm-lock.yaml
Changes:
- Updated JSX transform configuration from "jsx": "react" to "jsx": "react-jsx".
- Dropped support for React 16 as the new JSX runtime requires React 17 or higher.
=> chore(react): update JSX transform to "react-jsx" and drop React 16 support

.changeset/ninety-trains-wave.md, packages/solid/package.json, packages/solid/tsconfig.build.json, packages/solid/tsup.config.ts, pnpm-lock.yaml
simplified `tsup.config.ts` config by removing `tsup-preset-solid` and utilizing `esbuild-plugin-solid` directly.
only modified default values of tsup config.
separate version of extended `tsconfig.build.json` for tsup build.
writing `package.json` on build step is not a necessary thing like `tsup-preset-solid` does.
✅ Tested with `dotlottie-solid-example`
=> refactor(solid): remove preset and simplify `tsup` configuration

.changeset/neat-turtles-sip.md, packages/react/package.json, packages/react/src/dotlottie-worker.tsx, packages/react/src/dotlottie.tsx, packages/react/src/use-dotlottie-worker.tsx, packages/react/src/use-dotlottie.tsx, pnpm-lock.yaml
- Update the peer dependencies of the `@lottiefiles/dotlottie-react` package and upgrade the React version to v19.
Fixes #426
=> feat: React v19 upgrade

.changeset/sixty-shoes-roll.md, packages/react/src/base-dotlottie-react.tsx, packages/react/tests/dotlottie-react.spec.tsx
=> fix(react): add missing `layout` prop

packages/react/README.md
Fixes #435
Update the description of `autoResizeCanvas` in `packages/react/README.md` to reflect its move to `renderConfig.autoResize`.
=> Fix wrong description of autoResizeCanvas in README

.changeset/nice-hats-fix.md, packages/web/src/dotlottie.ts
This update rounds `nextFrame` to two decimal places for smoother animations and improved performance.
=> perf(web): update nextFrame precision for perf

.changeset/quick-actors-work.md, packages/web/src/dotlottie.ts, packages/web/src/worker/dotlottie.ts, packages/web/tests/dotlottie.test.ts
=> fix(web): 🐛 fail to resize when canvas element is hidden

.changeset/popular-ladybugs-carry.md, packages/web/src/dotlottie.ts
=> fix: prevent IndexSizeError when buffer size doesn't match canvas dimensions

.changeset/common-tires-rush.md, packages/vue/src/dotlottie.ts
Adding missing options and watcher for vue package, slightly refactored code.
while i was using react code as reference of how to handle these options I found this: https://github.com/LottieFiles/dotlottie-web/blob/main/packages/react/src/base-dotlottie-react.tsx#L185-L189 and github.com/LottieFiles/dotlottie-web/blob/main/packages/react/src/base-dotlottie-react.tsx#L176-L180
wondering if this is correct as i think `src` and `data` should place after `...configRef.current`.
=> feat(vue): add missing options
