package.json

chore(deps): update dependency @changesets/cli to v2.26.2 (#1)

---

README.md

chore: 🤖 center .lottie logo in the README

---

.changeset/sweet-comics-confess.md
apps/dotlottie-web-example/src/main.ts
packages/web/README.md
packages/web/src/dotlottie.ts
packages/web/src/index.ts
packages/web/src/renderer-wasm/bin/renderer.js
packages/web/src/renderer-wasm/index.ts
packages/web/tsconfig.build.json
packages/web/wasm_x86_i686.txt

fix: 🐛 loading wasm binaries

---

.changeset/witty-cougars-whisper.md
packages/web/src/dotlottie.ts
packages/web/src/renderer-wasm/index.ts

fix: 🐛 load .wasm binary only once

---

.changeset/cuddly-laws-clap.md
apps/dotlottie-web-example/src/main.ts
packages/web/README.md
packages/web/src/dotlottie.ts
packages/web/src/event-manager.ts

feat: 🎸 add destroy method

---

.changeset/proud-trains-shop.md
apps/dotlottie-web-example/src/main.ts
packages/web/README.md
packages/web/src/dotlottie.ts

Add `load` method
`@lottiefiles/dotlottie-web`

feat: 🎸 add load method

---

apps/dotlottie-web-example/src/styles.css
packages/web/README.md

chore: 🤖 update README

---

.changeset/twenty-chairs-return.md
apps/dotlottie-web-example/src/main.ts
packages/web/README.md
packages/web/src/dotlottie.ts

feat: 🎸 backgroundColor

---

README.md
packages/web/README.md

chore: 🤖 add controlling animation playback example

---

.changeset/sour-ghosts-double.md
.changeset/tall-zoos-shout.md
apps/dotlottie-web-example/src/main.ts
packages/web/README.md
packages/web/src/dotlottie.ts

This PR introduces the `setMode` method in the `DotLottie`. ensures a seamless transition when changing the playback mode of an animation, maintaining the continuity and flow of the animation.

feat: 🎸 setMode

---

.changeset/gentle-ads-obey.md
apps/dotlottie-web-example/src/main.ts
packages/web/README.md
packages/web/src/dotlottie.ts
packages/web/src/event-manager.ts

feat: 🎸 add destroy event

---

.changeset/olive-comics-fold.md
packages/web/src/dotlottie.ts

Ensure the canvas is cleared before loading a new animation.

fix: 🐛 ensure the canvas is cleared before loading a new animation

---

.changeset/loud-files-add.md
packages/web/README.md
packages/web/src/dotlottie.ts

feat: 🎸 add autoplay getter

---

.changeset/plenty-paws-kick.md
packages/web/src/dotlottie.ts

fix: 🐛 unfreeze on play

---

.changeset/smart-comics-ring.md
apps/dotlottie-web-example/src/main.ts
packages/web/src/dotlottie.ts

fix: 🐛 correct regression in animation play check before raf

---

.changeset/wet-jeans-perform.md
apps/dotlottie-web-node-example/package.json
packages/web/README.md
packages/web/src/dotlottie.ts
packages/web/tests/dotlottie/load.test.ts

feat: 🎸 add isLoaded property

---

.changeset/mean-rabbits-type.md
apps/dotlottie-react-example/src/App.tsx
apps/dotlottie-react-example/src/main.tsx
packages/react/src/use-dotlottie.tsx

feat(react): 🎸 freeze animation when hidden

---

.changeset/config.json
apps/dotlottie-react-example/package.json
apps/dotlottie-wc-example/package.json
apps/dotlottie-web-example/package.json
apps/dotlottie-web-node-example/package.json

chore: 🤖 fix changeset config

---

packages/web/tests/dotlottie/stop.test.ts

chore: 🤖 fix stop playback tests

---

.github/workflows/main.yml

chore: 🤖 changeset to skip duplicate tags

---

.changeset/wet-hounds-beg.md
packages/web/src/constants.ts

fix: 🐛 IS_NODE -> cannot read properties of undefined

---

README.md
packages/react/README.md
packages/web/README.md

chore: 🤖 update examples in the README's

---

.changeset/gold-geckos-cough.md
packages/web/src/animation-frame-manager.ts
packages/web/src/constants.ts

fix: 🐛 animation loop not starting in remix apps

---

README.md
packages/web/README.md

chore: 🤖 add multi animations .lottie file example in README

---

apps/dotlottie-viewer/src/store/viewer-slice.ts

fix: 🐛 url issue

---

.changeset/chilly-lobsters-shave.md
packages/web/src/core/dotlottie-wasm-loader.ts

chore(web): 🤖 log error of loading the initial WASM URL

---

package.json
pnpm-lock.yaml

fix(pnpm): 🐛 size-limit script

---

.changeset/fast-garlics-retire.md
apps/dotlottie-react-example/src/client-entry.tsx
apps/dotlottie-react-example/src/server-entry.tsx
packages/react/src/use-dotlottie.tsx

fix(react): 🐛 dotlottieRefCallback null instance in strict mode

---

.changeset/late-crabs-think.md
packages/react/src/use-dotlottie.tsx

fix: 🐛 remove the unncessary intersection observer debounce

---

packages/web/README.md

fix: updated readme with interactivity

---

packages/web/README.md

docs: layout property required

---

packages/vue/README.md

docs(vue): ✏️ Fix typo

---

apps/dotlottie-viewer/src/components/side-panel.tsx

chore: update dotLottie documentation link in side panel

---

.github/workflows/main.yml
packages/web/jsr.json
packages/web/package.json

chore: add jsr-release workflow and update package.json exports

---

.github/workflows/main.yml

chore: update jsr publish command in main.yml

---

.changeset/friendly-dots-reflect.md
packages/solid/package.json

fix: added provenance

---

.changeset/chatty-pillows-retire.md
.github/workflows/main.yml

fix: added id-token write for npm-release job

---

.changeset/silly-dragons-wash.md
.github/workflows/main.yml
packages/react/package.json
packages/solid/package.json
packages/svelte/package.json
packages/vue/package.json
packages/wc/package.json
packages/web/package.json

feat: added npm provenance

---

.github/workflows/main.yml

Update and simplify the workflow to address dual repository publishing.

chore: fix github workflow

---

.github/workflows/main.yml

ci: update permissions for publish-viewer job in main.yml

---

.changeset/warm-crabs-ring.md
packages/web/src/resize-observer.ts

fix: 🐛 clear timeouts in resize observer to avoid mem leaks

---

.changeset/wicked-frogs-rhyme.md
packages/web/src/worker/dotlottie.ts
packages/web/src/worker/dotlottie.worker.ts
packages/web/tests/dotlottie.test.ts
packages/web/vitest.config.ts

fix: 🐛 resolve race condition in DotLottieWorker destroy method

---

.changeset/real-cups-cry.md
.changeset/wicked-frogs-rhyme.md
.github/workflows/main.yml
packages/react/src/base-dotlottie-react.tsx
packages/react/tests/dotlottie-react.spec.tsx
packages/web/src/dotlottie.ts
packages/web/src/worker/dotlottie.ts
packages/web/src/worker/dotlottie.worker.ts
packages/web/tests/dotlottie.test.ts
packages/web/vitest.config.ts

fix: 🐛 cannot transfer control from a canvas for more than one

---

.changeset/new-walls-battle.md
.changeset/pre.json
.github/workflows/main.yml
packages/react/CHANGELOG.md
packages/react/package.json
packages/solid/CHANGELOG.md
packages/solid/package.json
packages/svelte/CHANGELOG.md
packages/svelte/package.json
packages/vue/CHANGELOG.md
packages/vue/package.json
packages/wc/CHANGELOG.md
packages/wc/package.json
packages/web/CHANGELOG.md
packages/web/package.json
packages/web/src/dotlottie.ts
packages/web/src/worker/dotlottie.ts
packages/web/src/worker/dotlottie.worker.ts
packages/web/src/worker/types.ts
packages/web/tests/dotlottie.test.ts

chore(release): pre-release to latest

---

.changeset/long-tables-accept.md

chore: update changelog

---

.changeset/violet-scissors-tickle.md
.size-limit.cjs
packages/react/package.json
packages/solid/package.json
packages/svelte/package.json
packages/vue/package.json
packages/web/package.json

chore: add sideEffects flag to package.json for better tree-shaking

---

.changeset/lemon-brooms-peel.md
packages/web/src/dotlottie.ts

fix: newValue and oldValue parameters in state machine input callbacks

---

packages/web/README.md

docs: add detailed browser requirements and minimum versions
